# Generated by Django 4.0.4 on 2022-05-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=15)),
            ],
        ),
    ]
