# Generated by Django 4.0.4 on 2022-05-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='int',
        ),
    ]
