# Generated by Django 4.0.4 on 2022-06-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_loginfunc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('senha', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('profissional', models.CharField(choices=[('Assistencia Tecnica', 'assistencia tecnica'), ('Professor', 'professor'), ('Mecanico', 'mecanico'), ('Consultoria', 'consultoria'), ('Tecnologia', 'tecnologia'), ('Eventos', 'eventos'), ('Beleza', 'beleza'), ('Reparos', 'reparos'), ('Saude', 'saude'), ('Domestico', 'domestico'), ('Motociclista', 'motociclista')], max_length=25)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginFunc',
        ),
    ]
