# Generated by Django 4.0.4 on 2022-06-27 01:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_imagemperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemperfil',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='usuario', variations={'thumb': (124, 124)}, verbose_name='Imagem'),
        ),
    ]
